In [1]:
import numpy as np

Construct system of linear equations

In [2]:
A = np.array([
    [2, -1, 1, 1],
    [1, 2, -1, -1],
    [-1, 2, 2, 2],
    [1, -1, 2, 1]
], dtype=np.dtype(float))

b = np.array([6, 3, 14, 8], dtype=np.dtype(float))

Determinant calculation and System solve

In [3]:
determinant = np.linalg.det(A)
determinant

-16.999999999999993

In [4]:
x = np.linalg.solve(A, b)
x

array([2., 3., 4., 1.])

Elementary functions

In [5]:
def row_mul(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print(row_mul(A, 2, 3))

[[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-3.  6.  6.  6.]
 [ 1. -1.  2.  1.]]


In [6]:
def row_sum(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[row_num_2] += M_new[row_num_1]

    return M_new


print(row_sum(A, 1, 2))

[[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [ 0.  4.  1.  1.]
 [ 1. -1.  2.  1.]]
